language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# - "pypy" is temporarily removed until a version with bug 1728 fixed is released
# command to install dependencies
install:
  - pip install coveralls
  - pip install pytest-cov
  - pip install .
# command to run tests
script:
  - coverage run --source=peval setup.py test
  - coverage report -m
after_success:
  coveralls
